server:
  port: 6660

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://your database address/easy_en
    username: admin
    password: iloveSCU

  mail:
    host: smtp.163.com
    username: easyenglishscu@163.com
    password: MHSDFJXRSUSOEYBN
    default-encoding: UTF-8

  data:
    redis:
      password:
      database: 0
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml


gpt:
  api-key: "Your key"
  model: "The model you use"
  maxTokens: 2048
  temperature: 0.5
  timeout: 90000

proxy:
  host: "ip address of proxy host" //使用本机上的clash等梯子则localhost即可
  port: 4560 // 如上则7890




