server:
  port: 6660

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://121.48.200.8:9000/easy_en
    username: admin
    password: iloveSCU

mybatis:
  mapper-locations: classpath:mapper/*.xml


gpt:
  api-key: "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"
  model: "text-davinci-003"
  maxTokens: 2048
  temperature: 0.5

